### ISSUE TITLE
Working version without MMM-PIR-Sensor

### ISSUE THREAD

**Issue by thedoorsfanatic** [jclarke0000/MMM-MyWordClock#3]
Hi,

is there a way to use your module without MMM-PIR-Sensor installed? I just wanna show the word clock on my screen.

If this is not possibe would you please also include a working config for MMM-PIR-Sensor

Thanks a lot!
Chris from Munich, Germany

**Comment by jclarke0000** [comment]
I've just made an update that allows you to specify the message that cancels the screensaver.  See the README for this module to see how to use it.  For example, if you're using EXT-Pir you can specify `wakeMessage: "EXT_SCREEN-WAKEUP"` to have the screensaver canceled by motion detected by the EXT-Pir module.

If you want to use MMM-PIR-Sensor, then there's no special configuration you need to make.  This module defaults to reacting to the message MMM-PIR-Sensor emits when it detects motion.  As long as MMM-PIR-Sensor is properly configured with your motion sensor, everything will work.
