### ISSUE TITLE
Work with a camera as movement detector

### ISSUE THREAD

**Issue by airart** [jclarke0000/MMM-MyWordClock#4]
Can'i use a usb cam as a motion detector to exit clock mode ?

**Comment by jclarke0000** [comment]
I know this is a bit late to the party, but I just published an update that allows you to specify the message that will cancel the screensaver.  So whatever module you're using to detect motion with a web cam, check its docs for the message it emits when motion is detected.

Specify that message in the config for this module using the new "wakeMessage" configuration parameter (See the README for details).
